### ISSUE TITLE
Card scrolling frequently freezes

### ISSUE THREAD

**Issue by gappleto97** [devgianlu/PretendYoureXyzzyAndroid#10]
Screen recording here: https://imgur.com/a/12ocIBg

I am running this on a Pixel 2, Android 8.1.0

Great app, otherwise. Once this is fixed I think I will show my friends so we can play

**Comment by gappleto97** [comment]
Sorry, gave a dead link by mistake. here is the actual screen grab

**Comment by gappleto97** [comment]
Sorry for the dead link. Here is the correct one. just strip the gz at the end. I renamed it because GitHub is picky about file extensions,
[MP4_20181114_010635.mp4.gz](https://github.com/devgianlu/PretendYoureXyzzyAndroid/files/2579950/MP4_20181114_010635.mp4.gz)

**Comment by devgianlu** [comment]
This is much difficult to debug than I thought, it will probably fix itself with #2.
