### ISSUE TITLE
F-Droid version heavily outdated and broken

### ISSUE THREAD

**Issue by sks316** [devgianlu/PretendYoureXyzzyAndroid#157]
The version of this app on F-Droid is heavily outdated and is actually completely broken (as in, it no longer works). It works when downloaded from the Google Play Store, but I prefer to use F-Droid where possible and the version available on it has not been updated since 2019. It seems to think the source code is no longer available, which is clearly not the case.

**Comment by devgianlu** [comment]
The updated version of the app no longer works without Google Services.

**Comment by sks316** [comment]
And the outdated version no longer works at all, if updating the F-Droid version isn't an option then it should be removed.

**Comment by devgianlu** [comment]
Didn't know the F-Droid version broke, I'll try to get in contact with them to have it removed.

**Comment by devgianlu** [comment]
https://gitlab.com/fdroid/fdroiddata/-/issues/2561

**Comment by devgianlu** [comment]
All done
