### ISSUE TITLE
Client has trouble keeping up with game time

### ISSUE THREAD

**Issue by Gymcap** [devgianlu/PretendYoureXyzzyAndroid#18]
It seems that with every game state change I have to refresh for the client to catch up.

**Comment by devgianlu** [comment]
That's a big sad given that I just rewrote the whole game logic. But also strange because I've never experienced this in my tests.

**Comment by Gymcap** [comment]
@devgianlu any way to give a useful log to help find the problem?

**Comment by devgianlu** [comment]
Yes, you can send me an email from the app, all the information I need is in there.

**Comment by Gymcap** [comment]
Having trouble recreating it, will send if it happens again.

**Comment by devgianlu** [comment]
I thought it was a constant issue, knowing it's occasional is a relief.

**Comment by Gymcap** [comment]
It happened in the first game I played, so I felt the same haha. Every game after so far seems fine though. :smiley:

**Comment by devgianlu** [comment]
I think this can be marked as solved. Reopen this if it happens again.
