### ISSUE TITLE
Change (un)locked icon colors

### ISSUE THREAD

**Issue by araspik** [devgianlu/PretendYoureXyzzyAndroid#22]
When scrolling through the game list it's really hard to differentiate between locked and unlocked games. If one (or both) of them had a different color it would be really helpful. Thanks! (P.S: Nice game)

**Comment by devgianlu** [comment]
Very simple, but should do the trick.

![screenshot_1544875468](https://user-images.githubusercontent.com/14827249/50042842-f1cfbc00-0069-11e9-8c62-83ca3cdd1811.png)
![screenshot_1544875452](https://user-images.githubusercontent.com/14827249/50042843-f1cfbc00-0069-11e9-9f10-f76c62ba1656.png)
