### ISSUE TITLE
[Feature Request] Chromecast Support

### ISSUE THREAD

**Issue by haydennyyy** [devgianlu/PretendYoureXyzzyAndroid#26]
It would be so awesome if you could do a CardCast-like thing with PYX through the app! 10/10 IGN would play again

**Comment by devgianlu** [comment]
I don't own a Chromecast and I have no idea on how this would work. Could you point out an app that works with it?

**Comment by haydennyyy** [comment]
Well, Cardcast would be a good example. I'm not sure about any OSS ones though... But basically the flow would be you start a game, have a button to cast it, and then the phone/tablet becomes a remote for the screen. You play cards on your phone, but everyone else's cards and the black card and stuff are all up on the screen.

**Comment by haydennyyy** [comment]
Doing a quick google search, it looks like Chromecast works with an HTML file served from somewhere... It's a shame. You'd need to implement an always-on webapp...

**Comment by haydennyyy** [comment]
https://github.com/vitalidze/chromecast-java-api-v2 There's a Java implementation

**Comment by devgianlu** [comment]
I'm sorry but that's not related to the app.

**Comment by haydennyyy** [comment]
It is related to the app though.

**Comment by haydennyyy** [comment]
The phone would act as a server, which would send information to the HTML page on the Chromecast.

**Comment by devgianlu** [comment]
It requires a lot of work and I don't think there'll be a lot of people using it. I might get on it, but not very soon for sure.

**Comment by haydennyyy** [comment]
That's fair I suppose. I'd help if Android Studio didn't almost blow up my laptop whenever I run it
