### ISSUE TITLE
Change clock icon in game view to an OK mark

### ISSUE THREAD

**Issue by bandithedoge** [devgianlu/PretendYoureXyzzyAndroid#28]
Might seem like a very minor thing, but the icons can get confusing, especially to new players.

**Comment by devgianlu** [comment]
You mean where the players are?

**Comment by bandithedoge** [comment]
Yes, the player list

**Comment by devgianlu** [comment]
It is a bit tricky to indicate in which state the player is. I'll think about changing the icons a little bit.

**Comment by bandithedoge** [comment]
Just replace the clock icon with another one
