### ISSUE TITLE
Add Privacy Policy.

### ISSUE THREAD

**Issue by HarryHeights** [devgianlu/PretendYoureXyzzyAndroid#29]
Hi! I'm Harry. Nice game, although I'm yet to fully grasp how to play it. I've been using my intuition. Well, I wanted to inquire if you had a privacy policy statement for the app. If you don't, it'd be nice to have one, and I can help you create it.

**Comment by devgianlu** [comment]
The current privacy policy is available [here](https://github.com/devgianlu/PretendYoureXyzzyAndroid/wiki/Privacy-Policy), but it has been generated with a random website. I do not currently need to update it.

BUT, I'm working on a little service to expand this app functionalities outside of the one already provided by the standard PYX servers. This service requires the user to register (email required), I do not know which data will be stored, but I do know I'll probably need to comply with GDPR. Can you help me? If so, can I contact you privately? Or is it fine to talk here?

**Comment by HarryHeights** [comment]
It is fine to talk here. I went through the existing policy. It's not bad. It just needs to be a little more definitive. Privacy policies are standardized documents. So you'll find every other privacy policy statement similar to what you have now. It just needs a little more precision.

**Comment by HarryHeights** [comment]
And yes, I can help

**Comment by devgianlu** [comment]
I'll get back to you when I know clearly what will be stored of each user.

**Comment by HarryHeights** [comment]
Alright. No qualms

**Comment by tyzoid** [comment]
Part of the challenge is it's up to each third party site owner to determine what gets logged and what doesn't.

**Comment by HarryHeights** [comment]
@tyzoid, that issue can be addressed in the policy statement by saying; third-party apps may have access to some personally identifiable details. Then place a disclaimer saying you are not responsible for the privacy policies of those third-party libraries or sites.
