### ISSUE TITLE
Failed Loading

### ISSUE THREAD

**Issue by mascali33** [devgianlu/PretendYoureXyzzyAndroid#30]
Hi @devgianlu !
I tried to install my own version of Pretend You're xyzzy and the web interface works but the app says:
```
1558118497836|2.8.13-standard|ERROR
Failed loading!

1558118497837|2.8.13-standard|ERROR
org.json.JSONException: Value <html><head><title>Apache of type java.lang.String cannot be converted to JSONObject
	at org.json.JSON.typeMismatch(JSON.java:112)
	at org.json.JSONObject.<init>(JSONObject.java:163)
	at org.json.JSONObject.<init>(JSONObject.java:176)
	at com.gianlu.pretendyourexyzzy.NetIO.Pyx.a(Pyx.java:21)
	at com.gianlu.pretendyourexyzzy.NetIO.Pyx.a(Pyx.java:7)
	at com.gianlu.pretendyourexyzzy.NetIO.Pyx.a(Pyx.java:38)
	at com.gianlu.pretendyourexyzzy.NetIO.Pyx.o(Pyx.java:1)
	at com.gianlu.pretendyourexyzzy.NetIO.Pyx.a(Pyx.java:2)
	at com.gianlu.pretendyourexyzzy.NetIO.qa.run(Pyx.java:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

And I don't really know how to make it work 😅 any idea ?
(I think it's from the fact that I use Apache2 mod_proxy to forward it to my container and the app don't expect it 🤔)

PS: Thanks for making this wonderful app :D

**Comment by devgianlu** [comment]
Are you able to play the game from the browser? Make sure your setup is working properly.

**Comment by mascali33** [comment]
Setup working properly (using untouched docker image [found here](https://hub.docker.com/r/emcniece/dockeryourxyzzy) (running in production mode)) and game playable from browser (tested with Chrome and Firefox)


Will try to see my Apache2 logs to see what does the app ask and what my server returns

**Comment by mascali33** [comment]
Look like my apache2 server returns error 500 with request /AjaxServlet (but with no body returns 200, investigating in code to see what the app ask :D)

**Comment by devgianlu** [comment]
`AjaxServlet` is the endpoint used for pretty much all the communication.

I wonder why Apache returns 500 to the app, but not the browser. Could you share your configuration?

**Comment by mascali33** [comment]
What configuration do you want exactly (because I don't really know where to search 😅)

here is the Apache2 Proxy config (will try to get the Tomcat Config)
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerName pyx.mascali.party
    ProxyPreserveHost On

    ProxyPass / http://127.0.0.1:4144/
    ProxyPassReverse / http://127.0.0.1:4144/

        ErrorLog ${APACHE_LOG_DIR}/error-pyx.log
        CustomLog ${APACHE_LOG_DIR}/access-pyx.log combined

SSLCertificateFile /etc/letsencrypt/live/pyx.mascali.party/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/pyx.mascali.party/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
Header always set Strict-Transport-Security "max-age=31536000"
Header always set Content-Security-Policy upgrade-insecure-requests
</VirtualHost>
</IfModule>
```

**Comment by mascali33** [comment]
Think I found something in error logs in the apache tomcat log, trying to figure what is going on :D

**Comment by mascali33** [comment]
YES ! Found the issue !! Was from the default sql database that was not filled with anything
Now working !

Thank you for trying to help me even if that was my fault :(

btw your app is the best !
