### ISSUE TITLE
Max. number of blank cards is hardcoded at 30

### ISSUE THREAD

**Issue by tyzoid** [devgianlu/PretendYoureXyzzyAndroid#32]
Some servers support more than the max of 30 - for example https://zy-a.us.notrly.xyz/ supports a blank limit of up to 100,000

https://github.com/devgianlu/PretendYoureXyzzyAndroid/blob/46414e53cb3c6bc9860baa3bcb1b1710007a51c8/app/src/main/java/com/gianlu/pretendyourexyzzy/NetIO/Models/Game.java#L219-L220

**Comment by devgianlu** [comment]
This needs a fix, but I don't remember if the server communicates these parameters. Will check.

**Comment by tyzoid** [comment]
I don't believe it does - I've been looking at the request dumps all day, and can't seem to find them.

**Comment by tyzoid** [comment]
If it helps - I might be able to prepare a PR to the upstream game server, but then it's on the site admins to update. That said - most use the default limit of 30 blank cards, so I'm not sure it's that bad of a solution.

**Comment by devgianlu** [comment]
I've created https://github.com/ajanata/PretendYoureXyzzy/pull/219 to get over this issue. If the PR gets merged, I'll then modify the code for the app.

**Comment by devgianlu** [comment]
I am actually working on a different solution which does a binary search to find out where the limit is. Will update this thread.

**Comment by devgianlu** [comment]
Fixed with 88aabf7f86a627a4ff30905435504c016a25d5ac.
