### ISSUE TITLE
Failed loading! message on startup

### ISSUE THREAD

**Issue by JustMeErazem** [devgianlu/PretendYoureXyzzyAndroid#5]
After opening the app it says "Failed loading" and there is an empty "Change menu" window with a "Manage" button on the lower left.

Edit: According to [pretendyoure.xyz](https://pretendyoure.xyz/zy/), 3/4 servers are down, the only one remaining is [THIRD-PARTY: Club Retard](https://xyzzy.clrtd.com/zy/), maybe it should be set as the default one?

Edit2: Even with only the working server enabled, the message persists and won't login.

**Comment by devgianlu** [comment]
The [api](https://pyx-discovery.gianlu.xyz/ListAll) is working fine. 

What happens if you click on the "Manage" button? Is the list still empty?

Clearing the app data will fix the issue I think (You'll lose the starred cards and decks).

**Comment by JustMeErazem** [comment]
The list is still empty, and this issue has occured immediately after installing and running the app from F-Droid.

**Comment by devgianlu** [comment]
I've just tried to reproduce this, but I got no errors. Can you try some APK for me?

**Comment by JustMeErazem** [comment]
Yes, sure, just send the links and I'll test them out. Have you tried the F-Droid-signed release though? Maybe that's where the issue lies. Also I have an Android Pie phone (Redmi Note 3) without google play services (LineageOS 16.0), if that helps.

**Comment by devgianlu** [comment]
Yeah, I've just tried. I'll publish a [pre-release](https://github.com/devgianlu/PretendYoureXyzzyAndroid/releases/tag/v2.610.1) for you to test. I've added a "preferences" button that you should be able to click before the dialog shows up. From there send me an email, this will attach the log files so that I can figure out what's happening.

You'll need to uninstall the F-Droid version because the signatures are different.

**Comment by JustMeErazem** [comment]
It says that the main servers are down, but it works now, I can choose a username and start playing. Thanks.

**Comment by devgianlu** [comment]
Nice! Quite strange how that happened, I'll have to dig a little bit.

**Comment by JustMeErazem** [comment]
I'm going to leave it to you to close the issue when you think it's appropriate :) Thanks again.
