### ISSUE TITLE
problematic game info on F-droid

### ISSUE THREAD

**Issue by bydariogamer** [devgianlu/PretendYoureXyzzyAndroid#63]
I downloaded the game from F-droid: the page told me the source code was no longer available but it seems it is... Maybe you want to check this, because many people won't download unless.
The game info tells the game depends on a non-free internet services. Please, can you explain this or change the connectivity so it is possible for players to create a room that their own mobile hosts and join by IP, or at least use only free standards?
Thanks for your time

**Comment by devgianlu** [comment]
The description is correct, this app relies permanently on the Firebase APIs in order for the Overloaded expansion to work (I may plan to not depend on them entirely in the future). See https://gitlab.com/fdroid/fdroiddata/-/issues/1933.

> Please, can you explain this or change the connectivity so it is possible for players to create a room that their own mobile hosts and join by IP, or at least use only free standards?

The server is actually open source at https://github.com/ajanata/PretendYoureXyzzy, but it is not possible to run it on mobile devices.
