### ISSUE TITLE
CrCast Deck Recovery Crash

### ISSUE THREAD

**Issue by MissEryka** [devgianlu/PretendYoureXyzzyAndroid#84]
When attempting to recover a deck from Cardcast the app goes to white or black screen and then crashes.

I do not have a Cardcast account. If that is a requirement then it should display an error message instead of trying to perform the action without credentials.

Also, on the deck recovery popup it should be clarified what you need to put into the box: deck code.

**Comment by devgianlu** [comment]
A Cardcast account is not required. The crash shouldn't happen. Could you send me a log file privately? You can do it from the preferences.

**Comment by devgianlu** [comment]
Fixed with b6a9e7894cf040e119abe9bbb02ce291857fa165
