### ISSUE TITLE
Player Block Not Fully Visible - Moto Z2 Play

### ISSUE THREAD

**Issue by MissEryka** [devgianlu/PretendYoureXyzzyAndroid#86]
![Screenshot_2020-12-31_045323](https://user-images.githubusercontent.com/76809959/103405398-f10d0400-4b24-11eb-9cbb-54099e209307.jpg)
The bottom of the page is cut off so that you can't see who is playing. You could make it so that the cards shrink to fit the whole page on different phone displays.

Motorola Z2 Play

**Comment by devgianlu** [comment]
This issue was discussed many times with the designer and I thought I fixed. The problem is to accomodate all device size while maintaining a reasonable layout. Will look into it again.
