### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by MissEryka** [devgianlu/PretendYoureXyzzyAndroid#87]
![Screenshot_2020-12-31_053356](https://user-images.githubusercontent.com/76809959/103406792-ebfe8380-4b29-11eb-86cf-18ed7c49b431.jpg)
Suggestion: adding/moving Players [list] button link from settings page to server game list page next to the Global Chat button link.

![Screenshot_2020-12-31_053624](https://user-images.githubusercontent.com/76809959/103406899-557e9200-4b2a-11eb-9648-d5f260b5d2e2.jpg)
Suggestion: adding/moving Metrics data to profile page, because it makes more sense to have it there? You can have it appropriately stylized to fit the rest of the design.

**Comment by devgianlu** [comment]
> adding/moving Players [list] button link from settings page to server game list page next to the Global Chat button link.

I can add a shortcut for sure.

> adding/moving Metrics data to profile page, because it makes more sense to have it there? You can have it appropriately stylized to fit the rest of the design.

Most people don't even know metrics exists. The feature that is used the most is to take metrics of the game which already has a dedicated button. I think that moving the metrics in the profile section would be cluttering and at the same time annoy some people that don't care about it.

**Comment by MissEryka** [comment]
I guess I misunderstood what the metrics page was for. I was thinking that
the profile page would list the number of games you have played, number of
games won, number of hands played/won as a win ratio. But if that isn't an
easy thing to add then don't worry about it.

**Comment by devgianlu** [comment]
This type of metrics are shown if you connect Google Play Games.

**Comment by MissEryka** [comment]
How do you connect to a Google Play Games account? I may have accidentally
skipped it when the new app installed? There should be a button on the
profile page under achievements for anyone who skipped it.

**Comment by devgianlu** [comment]
Forgot to mention that it is a paid feature.
