### ISSUE TITLE
Custom Deck 'Images From Link' Missing

### ISSUE THREAD

**Issue by MissEryka** [devgianlu/PretendYoureXyzzyAndroid#88]
On the app store page it lists this under the free features section:

"Add images (from link) to your custom decks"

Where is this found? It should be in the deck editor.

![Screenshot_2020-12-31_055825](https://user-images.githubusercontent.com/76809959/103407613-3e8d6f00-4b2d-11eb-8aed-13cbd6dde039.jpg)

**Comment by devgianlu** [comment]
![Screenshot_2020-12-31-12-32-09-555_com.gianlu.pretendyourexyzzy.jpg](https://user-images.githubusercontent.com/14827249/103408776-43214a00-4b64-11eb-9f31-ff894b845770.jpg)

**Comment by MissEryka** [comment]
Ok, I'm an idiot lol.. I hadn't gotten to the white cards yet in my deck..
my bad. But perhaps it should be clarified on the app store page that the
images are for your answer cards and not the deck itself? That is where my
misunderstanding came from. Thanks for your patience!

**Comment by devgianlu** [comment]
Ohh, got it. Changing it to "to your custom decks cards" should clarify it.
