### ISSUE TITLE
Can't see your card after playing it

### ISSUE THREAD

**Issue by m3tax** [devgianlu/PretendYoureXyzzyAndroid#9]
After playing your card(s) and getting to the "Waiting for other players" screen (which becomes "Waiting for the current round to end" after a refresh), ALL cards will show up as question marks, including your own.

Refreshing does make your card appear though, so fixing it could be just as easy as making the game refresh after ending your turn.

**Comment by devgianlu** [comment]
That shouldn't be a big deal to fix.

**Comment by devgianlu** [comment]
I won't do this in `v2.7.0` because I have to rewrite a great part of the logic.
